### ISSUE TITLE
Action 18 (HISCOM): Help - Using AVH Downloads section needs updating to reflect the new and improved downloads functionality (Donna)

### ISSUE THREAD

**Issue by DNAdl8** [hiscom/business#18]
Donna to amend and provide to Niels to add to static pages...

**Comment by acvaughan** [comment]
I've updated this (albeit briefly).

**Comment by acvaughan** [comment]
How do I close the issue?

**Comment by nielsklazenga** [comment]
I have just promoted you. Can you see the 'Close issue' or 'Close and comment' button, next to the 'Comment' button now?

It might actually be better to not close the issue, but put a label or milestone in, but I don't know how this repository is supposed to be managed (or why we even have the repository, since we decided to keep the Wiki).

**Comment by acvaughan** [comment]
No, just comment.

**Comment by nielsklazenga** [comment]
How about now?

**Comment by acvaughan** [comment]
Yes, now I have the option of 'Close and comment' (or just 'Close' before I started to comment) or 'Comment'. Thanks.
